// GENERATED by `supabase gen types` against project blcfeguqhnggyxvexggy
// (2026-07-17, after migrations through 20260101000700). Regenerate after
// every migration. Domain aliases the app imports live in types/database.ts.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      admin_users: {
        Row: {
          created_at: string
          email: string
          event_ids: string[]
          id: string
          role: Database["public"]["Enums"]["admin_role"]
          user_id: string | null
        }
        Insert: {
          created_at?: string
          email: string
          event_ids?: string[]
          id?: string
          role?: Database["public"]["Enums"]["admin_role"]
          user_id?: string | null
        }
        Update: {
          created_at?: string
          email?: string
          event_ids?: string[]
          id?: string
          role?: Database["public"]["Enums"]["admin_role"]
          user_id?: string | null
        }
        Relationships: []
      }
      attendees: {
        Row: {
          ac_contact_id: string | null
          bio: string | null
          checked_in_at: string | null
          company: string | null
          created_at: string
          dietary: string | null
          email: string
          event_id: string
          id: string
          interests: string[]
          last_seen_at: string | null
          name: string
          notification_prefs: Json
          photo_url: string | null
          push_token: string | null
          qr_token: string
          role: string | null
          updated_at: string
          user_id: string | null
          visibility: Database["public"]["Enums"]["attendee_visibility"]
        }
        Insert: {
          ac_contact_id?: string | null
          bio?: string | null
          checked_in_at?: string | null
          company?: string | null
          created_at?: string
          dietary?: string | null
          email: string
          event_id: string
          id?: string
          interests?: string[]
          last_seen_at?: string | null
          name: string
          notification_prefs?: Json
          photo_url?: string | null
          push_token?: string | null
          qr_token?: string
          role?: string | null
          updated_at?: string
          user_id?: string | null
          visibility?: Database["public"]["Enums"]["attendee_visibility"]
        }
        Update: {
          ac_contact_id?: string | null
          bio?: string | null
          checked_in_at?: string | null
          company?: string | null
          created_at?: string
          dietary?: string | null
          email?: string
          event_id?: string
          id?: string
          interests?: string[]
          last_seen_at?: string | null
          name?: string
          notification_prefs?: Json
          photo_url?: string | null
          push_token?: string | null
          qr_token?: string
          role?: string | null
          updated_at?: string
          user_id?: string | null
          visibility?: Database["public"]["Enums"]["attendee_visibility"]
        }
        Relationships: [
          {
            foreignKeyName: "attendees_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
        ]
      }
      auction_items: {
        Row: {
          created_at: string
          current_bid: number | null
          current_bidder_id: string | null
          description: string | null
          ends_at: string
          event_id: string
          id: string
          is_open: boolean
          name: string
          photo_url: string | null
          starting_bid: number
          updated_at: string
          winner_id: string | null
        }
        Insert: {
          created_at?: string
          current_bid?: number | null
          current_bidder_id?: string | null
          description?: string | null
          ends_at: string
          event_id: string
          id?: string
          is_open?: boolean
          name: string
          photo_url?: string | null
          starting_bid: number
          updated_at?: string
          winner_id?: string | null
        }
        Update: {
          created_at?: string
          current_bid?: number | null
          current_bidder_id?: string | null
          description?: string | null
          ends_at?: string
          event_id?: string
          id?: string
          is_open?: boolean
          name?: string
          photo_url?: string | null
          starting_bid?: number
          updated_at?: string
          winner_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "auction_items_current_bidder_id_fkey"
            columns: ["current_bidder_id"]
            isOneToOne: false
            referencedRelation: "attendees"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "auction_items_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "auction_items_winner_id_fkey"
            columns: ["winner_id"]
            isOneToOne: false
            referencedRelation: "attendees"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_log: {
        Row: {
          action: string
          admin_user_id: string | null
          created_at: string
          entity: string
          entity_id: string | null
          id: string
          payload: Json
        }
        Insert: {
          action: string
          admin_user_id?: string | null
          created_at?: string
          entity: string
          entity_id?: string | null
          id?: string
          payload?: Json
        }
        Update: {
          action?: string
          admin_user_id?: string | null
          created_at?: string
          entity?: string
          entity_id?: string | null
          id?: string
          payload?: Json
        }
        Relationships: [
          {
            foreignKeyName: "audit_log_admin_user_id_fkey"
            columns: ["admin_user_id"]
            isOneToOne: false
            referencedRelation: "admin_users"
            referencedColumns: ["id"]
          },
        ]
      }
      bids: {
        Row: {
          amount: number
          attendee_id: string
          created_at: string
          id: string
          item_id: string
        }
        Insert: {
          amount: number
          attendee_id: string
          created_at?: string
          id?: string
          item_id: string
        }
        Update: {
          amount?: number
          attendee_id?: string
          created_at?: string
          id?: string
          item_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "bids_attendee_id_fkey"
            columns: ["attendee_id"]
            isOneToOne: false
            referencedRelation: "attendees"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bids_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "auction_items"
            referencedColumns: ["id"]
          },
        ]
      }
      check_ins: {
        Row: {
          attendee_id: string
          created_at: string
          day: string
          id: string
          source: string
        }
        Insert: {
          attendee_id: string
          created_at?: string
          day?: string
          id?: string
          source?: string
        }
        Update: {
          attendee_id?: string
          created_at?: string
          day?: string
          id?: string
          source?: string
        }
        Relationships: [
          {
            foreignKeyName: "check_ins_attendee_id_fkey"
            columns: ["attendee_id"]
            isOneToOne: false
            referencedRelation: "attendees"
            referencedColumns: ["id"]
          },
        ]
      }
      connections: {
        Row: {
          attendee_a: string
          attendee_b: string
          created_at: string
          event_id: string
          id: string
          note: string | null
          source: Database["public"]["Enums"]["connection_source"]
        }
        Insert: {
          attendee_a: string
          attendee_b: string
          created_at?: string
          event_id: string
          id?: string
          note?: string | null
          source?: Database["public"]["Enums"]["connection_source"]
        }
        Update: {
          attendee_a?: string
          attendee_b?: string
          created_at?: string
          event_id?: string
          id?: string
          note?: string | null
          source?: Database["public"]["Enums"]["connection_source"]
        }
        Relationships: [
          {
            foreignKeyName: "connections_attendee_a_fkey"
            columns: ["attendee_a"]
            isOneToOne: false
            referencedRelation: "attendees"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "connections_attendee_b_fkey"
            columns: ["attendee_b"]
            isOneToOne: false
            referencedRelation: "attendees"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "connections_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
        ]
      }
      daily_suggestions: {
        Row: {
          attendee_id: string
          created_at: string
          for_date: string
          id: string
          rationale: Json
          suggested_attendee_ids: string[]
          suggested_partner_ids: string[]
        }
        Insert: {
          attendee_id: string
          created_at?: string
          for_date: string
          id?: string
          rationale?: Json
          suggested_attendee_ids?: string[]
          suggested_partner_ids?: string[]
        }
        Update: {
          attendee_id?: string
          created_at?: string
          for_date?: string
          id?: string
          rationale?: Json
          suggested_attendee_ids?: string[]
          suggested_partner_ids?: string[]
        }
        Relationships: [
          {
            foreignKeyName: "daily_suggestions_attendee_id_fkey"
            columns: ["attendee_id"]
            isOneToOne: false
            referencedRelation: "attendees"
            referencedColumns: ["id"]
          },
        ]
      }
      events: {
        Row: {
          created_at: string
          end_date: string
          geofence_radius_m: number | null
          id: string
          name: string
          settings: Json
          start_date: string
          updated_at: string
          venue: string | null
          venue_lat: number | null
          venue_lng: number | null
        }
        Insert: {
          created_at?: string
          end_date: string
          geofence_radius_m?: number | null
          id?: string
          name: string
          settings?: Json
          start_date: string
          updated_at?: string
          venue?: string | null
          venue_lat?: number | null
          venue_lng?: number | null
        }
        Update: {
          created_at?: string
          end_date?: string
          geofence_radius_m?: number | null
          id?: string
          name?: string
          settings?: Json
          start_date?: string
          updated_at?: string
          venue?: string | null
          venue_lat?: number | null
          venue_lng?: number | null
        }
        Relationships: []
      }
      faqs: {
        Row: {
          answer: string
          created_at: string
          event_id: string
          id: string
          order_index: number
          question: string
        }
        Insert: {
          answer: string
          created_at?: string
          event_id: string
          id?: string
          order_index?: number
          question: string
        }
        Update: {
          answer?: string
          created_at?: string
          event_id?: string
          id?: string
          order_index?: number
          question?: string
        }
        Relationships: [
          {
            foreignKeyName: "faqs_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
        ]
      }
      gallery_items: {
        Row: {
          caption: string | null
          created_at: string
          event_id: string
          id: string
          is_official: boolean
          taken_at: string | null
          taken_by: string | null
          url: string
        }
        Insert: {
          caption?: string | null
          created_at?: string
          event_id: string
          id?: string
          is_official?: boolean
          taken_at?: string | null
          taken_by?: string | null
          url: string
        }
        Update: {
          caption?: string | null
          created_at?: string
          event_id?: string
          id?: string
          is_official?: boolean
          taken_at?: string | null
          taken_by?: string | null
          url?: string
        }
        Relationships: [
          {
            foreignKeyName: "gallery_items_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "gallery_items_taken_by_fkey"
            columns: ["taken_by"]
            isOneToOne: false
            referencedRelation: "attendees"
            referencedColumns: ["id"]
          },
        ]
      }
      notes: {
        Row: {
          ai_summary: string | null
          ai_summary_generated_at: string | null
          attendee_id: string
          body: string
          created_at: string
          follow_up_questions: string[]
          id: string
          session_id: string | null
          updated_at: string
        }
        Insert: {
          ai_summary?: string | null
          ai_summary_generated_at?: string | null
          attendee_id: string
          body?: string
          created_at?: string
          follow_up_questions?: string[]
          id?: string
          session_id?: string | null
          updated_at?: string
        }
        Update: {
          ai_summary?: string | null
          ai_summary_generated_at?: string | null
          attendee_id?: string
          body?: string
          created_at?: string
          follow_up_questions?: string[]
          id?: string
          session_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "notes_attendee_id_fkey"
            columns: ["attendee_id"]
            isOneToOne: false
            referencedRelation: "attendees"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notes_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      notification_recipients: {
        Row: {
          attendee_id: string
          delivered_at: string | null
          notification_id: string
          opened_at: string | null
        }
        Insert: {
          attendee_id: string
          delivered_at?: string | null
          notification_id: string
          opened_at?: string | null
        }
        Update: {
          attendee_id?: string
          delivered_at?: string | null
          notification_id?: string
          opened_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "notification_recipients_attendee_id_fkey"
            columns: ["attendee_id"]
            isOneToOne: false
            referencedRelation: "attendees"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notification_recipients_notification_id_fkey"
            columns: ["notification_id"]
            isOneToOne: false
            referencedRelation: "notifications"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          body: string
          created_at: string
          data: Json
          event_id: string
          id: string
          scheduled_at: string | null
          sent_at: string | null
          sent_by: string | null
          target_segment: Json
          title: string
          type: Database["public"]["Enums"]["notification_type"]
        }
        Insert: {
          body: string
          created_at?: string
          data?: Json
          event_id: string
          id?: string
          scheduled_at?: string | null
          sent_at?: string | null
          sent_by?: string | null
          target_segment?: Json
          title: string
          type: Database["public"]["Enums"]["notification_type"]
        }
        Update: {
          body?: string
          created_at?: string
          data?: Json
          event_id?: string
          id?: string
          scheduled_at?: string | null
          sent_at?: string | null
          sent_by?: string | null
          target_segment?: Json
          title?: string
          type?: Database["public"]["Enums"]["notification_type"]
        }
        Relationships: [
          {
            foreignKeyName: "notifications_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
        ]
      }
      partner_interest: {
        Row: {
          ac_event_emitted_at: string | null
          attendee_id: string
          created_at: string
          id: string
          partner_id: string
        }
        Insert: {
          ac_event_emitted_at?: string | null
          attendee_id: string
          created_at?: string
          id?: string
          partner_id: string
        }
        Update: {
          ac_event_emitted_at?: string | null
          attendee_id?: string
          created_at?: string
          id?: string
          partner_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "partner_interest_attendee_id_fkey"
            columns: ["attendee_id"]
            isOneToOne: false
            referencedRelation: "attendees"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "partner_interest_partner_id_fkey"
            columns: ["partner_id"]
            isOneToOne: false
            referencedRelation: "partners"
            referencedColumns: ["id"]
          },
        ]
      }
      partners: {
        Row: {
          contact_email: string | null
          created_at: string
          description: string | null
          display_order: number | null
          event_id: string
          id: string
          is_featured: boolean
          logo_url: string | null
          name: string
          solutions_content: string | null
          tags: string[]
          updated_at: string
          website_url: string | null
        }
        Insert: {
          contact_email?: string | null
          created_at?: string
          description?: string | null
          display_order?: number | null
          event_id: string
          id?: string
          is_featured?: boolean
          logo_url?: string | null
          name: string
          solutions_content?: string | null
          tags?: string[]
          updated_at?: string
          website_url?: string | null
        }
        Update: {
          contact_email?: string | null
          created_at?: string
          description?: string | null
          display_order?: number | null
          event_id?: string
          id?: string
          is_featured?: boolean
          logo_url?: string | null
          name?: string
          solutions_content?: string | null
          tags?: string[]
          updated_at?: string
          website_url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "partners_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
        ]
      }
      pending_connections: {
        Row: {
          captured_company: string | null
          captured_email: string | null
          captured_name: string | null
          captured_phone: string | null
          card_image_url: string | null
          created_at: string
          event_id: string
          id: string
          initiator_id: string
          resolved_at: string | null
          resolved_attendee_id: string | null
        }
        Insert: {
          captured_company?: string | null
          captured_email?: string | null
          captured_name?: string | null
          captured_phone?: string | null
          card_image_url?: string | null
          created_at?: string
          event_id: string
          id?: string
          initiator_id: string
          resolved_at?: string | null
          resolved_attendee_id?: string | null
        }
        Update: {
          captured_company?: string | null
          captured_email?: string | null
          captured_name?: string | null
          captured_phone?: string | null
          card_image_url?: string | null
          created_at?: string
          event_id?: string
          id?: string
          initiator_id?: string
          resolved_at?: string | null
          resolved_attendee_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "pending_connections_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pending_connections_initiator_id_fkey"
            columns: ["initiator_id"]
            isOneToOne: false
            referencedRelation: "attendees"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pending_connections_resolved_attendee_id_fkey"
            columns: ["resolved_attendee_id"]
            isOneToOne: false
            referencedRelation: "attendees"
            referencedColumns: ["id"]
          },
        ]
      }
      podcast_episodes: {
        Row: {
          audio_url: string
          description: string | null
          duration_seconds: number | null
          episode_url: string | null
          event_id: string
          id: string
          published_at: string
          title: string
        }
        Insert: {
          audio_url: string
          description?: string | null
          duration_seconds?: number | null
          episode_url?: string | null
          event_id: string
          id?: string
          published_at: string
          title: string
        }
        Update: {
          audio_url?: string
          description?: string | null
          duration_seconds?: number | null
          episode_url?: string | null
          event_id?: string
          id?: string
          published_at?: string
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "podcast_episodes_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
        ]
      }
      question_upvotes: {
        Row: {
          attendee_id: string
          created_at: string
          question_id: string
        }
        Insert: {
          attendee_id: string
          created_at?: string
          question_id: string
        }
        Update: {
          attendee_id?: string
          created_at?: string
          question_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "question_upvotes_attendee_id_fkey"
            columns: ["attendee_id"]
            isOneToOne: false
            referencedRelation: "attendees"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "question_upvotes_question_id_fkey"
            columns: ["question_id"]
            isOneToOne: false
            referencedRelation: "public_questions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "question_upvotes_question_id_fkey"
            columns: ["question_id"]
            isOneToOne: false
            referencedRelation: "questions"
            referencedColumns: ["id"]
          },
        ]
      }
      questions: {
        Row: {
          anonymous: boolean
          answered_at: string | null
          attendee_id: string
          body: string
          created_at: string
          event_id: string
          id: string
          moderation_note: string | null
          session_id: string | null
          speaker_id: string | null
          status: Database["public"]["Enums"]["question_status"]
          upvotes: number
        }
        Insert: {
          anonymous?: boolean
          answered_at?: string | null
          attendee_id: string
          body: string
          created_at?: string
          event_id: string
          id?: string
          moderation_note?: string | null
          session_id?: string | null
          speaker_id?: string | null
          status?: Database["public"]["Enums"]["question_status"]
          upvotes?: number
        }
        Update: {
          anonymous?: boolean
          answered_at?: string | null
          attendee_id?: string
          body?: string
          created_at?: string
          event_id?: string
          id?: string
          moderation_note?: string | null
          session_id?: string | null
          speaker_id?: string | null
          status?: Database["public"]["Enums"]["question_status"]
          upvotes?: number
        }
        Relationships: [
          {
            foreignKeyName: "questions_attendee_id_fkey"
            columns: ["attendee_id"]
            isOneToOne: false
            referencedRelation: "attendees"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "questions_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "questions_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "questions_speaker_id_fkey"
            columns: ["speaker_id"]
            isOneToOne: false
            referencedRelation: "speakers"
            referencedColumns: ["id"]
          },
        ]
      }
      schedule_picks: {
        Row: {
          attendee_id: string
          created_at: string
          session_id: string
        }
        Insert: {
          attendee_id: string
          created_at?: string
          session_id: string
        }
        Update: {
          attendee_id?: string
          created_at?: string
          session_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "schedule_picks_attendee_id_fkey"
            columns: ["attendee_id"]
            isOneToOne: false
            referencedRelation: "attendees"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "schedule_picks_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      session_speakers: {
        Row: {
          session_id: string
          speaker_id: string
        }
        Insert: {
          session_id: string
          speaker_id: string
        }
        Update: {
          session_id?: string
          speaker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "session_speakers_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "session_speakers_speaker_id_fkey"
            columns: ["speaker_id"]
            isOneToOne: false
            referencedRelation: "speakers"
            referencedColumns: ["id"]
          },
        ]
      }
      sessions: {
        Row: {
          abstract: string | null
          capacity: number | null
          created_at: string
          end_at: string
          event_id: string
          id: string
          is_published: boolean
          room: string | null
          start_at: string
          tags: string[]
          title: string
          type: Database["public"]["Enums"]["session_type"]
          updated_at: string
        }
        Insert: {
          abstract?: string | null
          capacity?: number | null
          created_at?: string
          end_at: string
          event_id: string
          id?: string
          is_published?: boolean
          room?: string | null
          start_at: string
          tags?: string[]
          title: string
          type?: Database["public"]["Enums"]["session_type"]
          updated_at?: string
        }
        Update: {
          abstract?: string | null
          capacity?: number | null
          created_at?: string
          end_at?: string
          event_id?: string
          id?: string
          is_published?: boolean
          room?: string | null
          start_at?: string
          tags?: string[]
          title?: string
          type?: Database["public"]["Enums"]["session_type"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "sessions_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
        ]
      }
      speaker_followers: {
        Row: {
          attendee_id: string
          created_at: string
          speaker_id: string
        }
        Insert: {
          attendee_id: string
          created_at?: string
          speaker_id: string
        }
        Update: {
          attendee_id?: string
          created_at?: string
          speaker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "speaker_followers_attendee_id_fkey"
            columns: ["attendee_id"]
            isOneToOne: false
            referencedRelation: "attendees"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "speaker_followers_speaker_id_fkey"
            columns: ["speaker_id"]
            isOneToOne: false
            referencedRelation: "speakers"
            referencedColumns: ["id"]
          },
        ]
      }
      speakers: {
        Row: {
          bio: string | null
          company: string | null
          created_at: string
          display_order: number | null
          event_id: string
          headshot_url: string | null
          id: string
          linkedin_url: string | null
          name: string
          tags: string[]
          title: string | null
          updated_at: string
        }
        Insert: {
          bio?: string | null
          company?: string | null
          created_at?: string
          display_order?: number | null
          event_id: string
          headshot_url?: string | null
          id?: string
          linkedin_url?: string | null
          name: string
          tags?: string[]
          title?: string | null
          updated_at?: string
        }
        Update: {
          bio?: string | null
          company?: string | null
          created_at?: string
          display_order?: number | null
          event_id?: string
          headshot_url?: string | null
          id?: string
          linkedin_url?: string | null
          name?: string
          tags?: string[]
          title?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "speakers_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
        ]
      }
      sync_runs: {
        Row: {
          detail: Json
          finished_at: string | null
          id: string
          job: string
          ok: boolean | null
          started_at: string
        }
        Insert: {
          detail?: Json
          finished_at?: string | null
          id?: string
          job: string
          ok?: boolean | null
          started_at?: string
        }
        Update: {
          detail?: Json
          finished_at?: string | null
          id?: string
          job?: string
          ok?: boolean | null
          started_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      public_questions: {
        Row: {
          anonymous: boolean | null
          answered_at: string | null
          author_name: string | null
          body: string | null
          created_at: string | null
          event_id: string | null
          id: string | null
          session_id: string | null
          speaker_id: string | null
          status: Database["public"]["Enums"]["question_status"] | null
          upvotes: number | null
        }
        Relationships: [
          {
            foreignKeyName: "questions_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "questions_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "questions_speaker_id_fkey"
            columns: ["speaker_id"]
            isOneToOne: false
            referencedRelation: "speakers"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      cron_headers: { Args: never; Returns: Json }
      current_attendee_event_id: { Args: never; Returns: string }
      current_attendee_id: { Args: never; Returns: string }
      is_admin_for: { Args: { p_event_id: string }; Returns: boolean }
      place_bid: {
        Args: { p_amount: number; p_item_id: string }
        Returns: Json
      }
    }
    Enums: {
      admin_role: "owner" | "editor" | "moderator" | "viewer"
      attendee_visibility: "public" | "connections_only" | "hidden"
      connection_source: "qr_scan" | "business_card" | "manual" | "suggested"
      notification_type:
        | "session_starting"
        | "dont_miss"
        | "people_to_meet"
        | "partner_spotlight"
        | "auction"
        | "admin_announcement"
      question_status: "pending" | "approved" | "rejected" | "answered"
      session_type:
        | "keynote"
        | "panel"
        | "workshop"
        | "breakout"
        | "meal"
        | "social"
        | "admin"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      admin_role: ["owner", "editor", "moderator", "viewer"],
      attendee_visibility: ["public", "connections_only", "hidden"],
      connection_source: ["qr_scan", "business_card", "manual", "suggested"],
      notification_type: [
        "session_starting",
        "dont_miss",
        "people_to_meet",
        "partner_spotlight",
        "auction",
        "admin_announcement",
      ],
      question_status: ["pending", "approved", "rejected", "answered"],
      session_type: [
        "keynote",
        "panel",
        "workshop",
        "breakout",
        "meal",
        "social",
        "admin",
      ],
    },
  },
} as const
